2023-03-09T23:49:16.201+0800	INFO	instance/beat.go:640	Home path: [E:\code\云原生\git.imooc.com\dessple\pob] Config path: [E:\code\云原生\git.imooc.com\dessple\pob] Data path: [E:\code\云原生\git.imooc.com\dessple\pob\data] Logs path: [E:\code\云原生\git.imooc.com\dessple\pob\logs]
2023-03-09T23:49:16.202+0800	INFO	instance/beat.go:648	Beat ID: f781c3fd-0e4f-4897-a418-f8e76dba9b37
2023-03-09T23:49:16.202+0800	INFO	[beat]	instance/beat.go:976	Beat info	{"system_info": {"beat": {"path": {"config": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "data": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\data", "home": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "logs": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\logs"}, "type": "filebeat", "uuid": "f781c3fd-0e4f-4897-a418-f8e76dba9b37"}}}
2023-03-09T23:49:16.202+0800	INFO	[beat]	instance/beat.go:985	Build info	{"system_info": {"build": {"commit": "7aab6a9659749802201db8020c4f04b74cec2169", "libbeat": "7.9.3", "time": "2020-10-16T09:16:15.000Z", "version": "7.9.3"}}}
2023-03-09T23:49:16.202+0800	INFO	[beat]	instance/beat.go:988	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":12,"version":"go1.14.7"}}}
2023-03-09T23:49:16.288+0800	INFO	[beat]	instance/beat.go:992	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2023-02-22T12:12:32.4+08:00","name":"DESKTOP-8K1IJ5A","ip":["fe80::2184:6ead:541:5295/64","169.254.23.90/16","fe80::9911:c532:6924:c868/64","172.31.144.1/20","fe80::5483:90c1:b30b:785e/64","169.254.244.105/16","fe80::35a9:1db8:a1f4:da6a/64","169.254.163.202/16","fe80::3318:2c57:4ae5:c3d8/64","192.168.142.1/24","fe80::bf70:9708:c69e:1b8/64","192.168.115.1/24","fd26:a241:87f4::d1f/128","fd26:a241:87f4:0:ce3d:e1bc:8bc0:100d/64","fd26:a241:87f4:0:6033:66cf:eaa9:9167/128","fd26:a241:87f4:0:d99c:5e73:3d70:9989/128","fd26:a241:87f4:0:f5d9:16bb:d810:9e93/128","fe80::ab2f:5bad:e890:55ea/64","192.168.1.128/24","fe80::99f4:b0e5:2e1d:d9a4/64","169.254.216.66/16","::1/128","127.0.0.1/8"],"kernel_version":"10.0.19041.2604 (WinBuild.160101.0800)","mac":["d8:bb:c1:4f:6c:c8","00:15:5d:fd:2b:60","e2:e1:a9:19:7a:8b","e0:e1:a9:19:7a:8b","00:50:56:c0:00:01","00:50:56:c0:00:08","e0:e1:a9:19:7a:8b","00:1a:7d:da:71:15"],"os":{"family":"windows","platform":"windows","name":"Windows 10 Pro","version":"10.0","major":10,"minor":0,"patch":0,"build":"19045.2604"},"timezone":"CST","timezone_offset_sec":28800,"id":"dc5c532d-a6b6-404d-a9b8-261c7f04c685"}}}
2023-03-09T23:49:16.288+0800	INFO	[beat]	instance/beat.go:1021	Process info	{"system_info": {"process": {"cwd": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "exe": "D:\\filebeat-7.9.3-windows-x86_64\\filebeat.exe", "name": "filebeat.exe", "pid": 24820, "ppid": 1532, "start_time": "2023-03-09T23:49:16.017+0800"}}}
2023-03-09T23:49:16.288+0800	INFO	instance/beat.go:299	Setup Beat: filebeat; Version: 7.9.3
2023-03-09T23:49:16.288+0800	INFO	[publisher]	pipeline/module.go:113	Beat name: DESKTOP-8K1IJ5A
2023-03-09T23:49:16.288+0800	ERROR	fileset/modules.go:127	Not loading modules. Module directory not found: E:\code\云原生\git.imooc.com\dessple\pob\module
2023-03-09T23:49:16.288+0800	WARN	beater/filebeat.go:178	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:49:16.288+0800	INFO	instance/beat.go:450	filebeat start running.
2023-03-09T23:49:16.288+0800	INFO	[monitoring]	log/log.go:118	Starting metrics logging every 30s
2023-03-09T23:49:16.290+0800	INFO	memlog/store.go:119	Loading data file of 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat' succeeded. Active transaction id=0
2023-03-09T23:49:16.290+0800	INFO	memlog/store.go:124	Finished loading transaction log file for 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat'. Active transaction id=10
2023-03-09T23:49:16.290+0800	WARN	beater/filebeat.go:381	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:49:16.290+0800	INFO	[registrar]	registrar/registrar.go:109	States Loaded from registrar: 1
2023-03-09T23:49:16.290+0800	INFO	[crawler]	beater/crawler.go:71	Loading Inputs: 1
2023-03-09T23:49:16.291+0800	INFO	log/input.go:157	Configured paths: [E:\code\云原生\git.imooc.com\dessple\pob\*.log]
2023-03-09T23:49:16.291+0800	INFO	[crawler]	beater/crawler.go:141	Starting input (ID: 9579789163401830746)
2023-03-09T23:49:16.291+0800	INFO	[crawler]	beater/crawler.go:108	Loading and starting Inputs completed. Enabled inputs: 1
2023-03-09T23:49:16.291+0800	INFO	log/harvester.go:299	Harvester started for file: E:\code\云原生\git.imooc.com\dessple\pob\micro.log
2023-03-09T23:49:17.299+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:49:17.299+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:49:17.299+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(async(tcp://localhost:5044))
2023-03-09T23:49:23.187+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:49:23.187+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 1 reconnect attempt(s)
2023-03-09T23:49:23.187+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:49:23.187+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:49:29.389+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:49:29.389+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 2 reconnect attempt(s)
2023-03-09T23:49:29.389+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:49:29.389+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:49:39.287+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:49:39.287+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 3 reconnect attempt(s)
2023-03-09T23:49:39.287+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:49:39.287+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:49:46.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125,"time":{"ms":125}},"total":{"ticks":234,"time":{"ms":234},"value":234},"user":{"ticks":109,"time":{"ms":109}}},"handles":{"open":237},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":30140}},"memstats":{"gc_next":15265232,"memory_alloc":8363600,"memory_total":36932592,"rss":48353280},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":62,"added":64,"done":2},"harvester":{"files":{"1dc2b7ce-210a-4938-a97c-b7b6a7714118":{"last_event_published_time":"2023-03-09T23:49:16.292Z","last_event_timestamp":"2023-03-09T23:49:16.292Z","name":"E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\micro.log","read_offset":13286,"size":13286,"start_time":"2023-03-09T23:49:16.291Z"}},"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":62,"filtered":2,"published":62,"retry":186,"total":64}}},"registrar":{"states":{"current":1,"update":2},"writes":{"success":2,"total":2}},"system":{"cpu":{"cores":12}}}}}
2023-03-09T23:49:56.739+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:49:56.739+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 4 reconnect attempt(s)
2023-03-09T23:49:56.739+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:49:56.739+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:50:16.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":234},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":60140}},"memstats":{"gc_next":15265232,"memory_alloc":8469880,"memory_total":37038872,"rss":32768},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:50:20.195+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:50:20.195+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 5 reconnect attempt(s)
2023-03-09T23:50:20.195+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:50:20.195+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:50:46.303+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":234},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":90154}},"memstats":{"gc_next":15265232,"memory_alloc":8558992,"memory_total":37127984,"rss":8192},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"files":{"1dc2b7ce-210a-4938-a97c-b7b6a7714118":{"size":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:51:02.116+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:51:02.116+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 6 reconnect attempt(s)
2023-03-09T23:51:02.116+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:51:02.116+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:51:16.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":234},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":120140}},"memstats":{"gc_next":15265232,"memory_alloc":8868288,"memory_total":37437280},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":3,"added":3},"harvester":{"files":{"1dc2b7ce-210a-4938-a97c-b7b6a7714118":{"last_event_published_time":"2023-03-09T23:50:51.360Z","last_event_timestamp":"2023-03-09T23:50:51.360Z","read_offset":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":65,"published":3,"retry":62,"total":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:51:46.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":234},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":150140}},"memstats":{"gc_next":16435120,"memory_alloc":8282064,"memory_total":37545192,"rss":-3981312},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":3,"added":3},"harvester":{"files":{"1dc2b7ce-210a-4938-a97c-b7b6a7714118":{"last_event_published_time":"2023-03-09T23:51:16.363Z","last_event_timestamp":"2023-03-09T23:51:16.363Z","read_offset":486,"size":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"published":3,"total":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:52:01.381+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:52:01.381+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 7 reconnect attempt(s)
2023-03-09T23:52:01.381+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:52:01.381+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:52:16.294+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":239},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":180145}},"memstats":{"gc_next":16435120,"memory_alloc":8581264,"memory_total":37844392,"rss":8192},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:52:35.586+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:52:35.586+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 8 reconnect attempt(s)
2023-03-09T23:52:35.586+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:52:35.586+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:52:46.303+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":240},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":210154}},"memstats":{"gc_next":16435120,"memory_alloc":8666216,"memory_total":37929344,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"retry":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:53:16.304+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":240},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":240154}},"memstats":{"gc_next":16809248,"memory_alloc":8622016,"memory_total":38005208,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:53:26.908+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:53:26.908+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 9 reconnect attempt(s)
2023-03-09T23:53:26.908+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:53:26.908+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:53:46.294+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":240},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":270145}},"memstats":{"gc_next":16809248,"memory_alloc":8499680,"memory_total":38104744,"rss":-655360},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:54:12.787+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:54:12.787+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 10 reconnect attempt(s)
2023-03-09T23:54:12.787+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:54:12.787+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:54:16.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":245},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":300140}},"memstats":{"gc_next":16809248,"memory_alloc":8583144,"memory_total":38188208,"rss":61440},"runtime":{"goroutines":29}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"retry":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:54:46.289+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":244},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":330140}},"memstats":{"gc_next":16809248,"memory_alloc":8662688,"memory_total":38267752},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:55:04.741+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:55:04.741+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 11 reconnect attempt(s)
2023-03-09T23:55:04.741+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:55:04.741+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:55:16.296+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":246},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":360147}},"memstats":{"gc_next":16809248,"memory_alloc":8740968,"memory_total":38346032,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:55:46.293+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":246},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":390144}},"memstats":{"gc_next":16826032,"memory_alloc":8431776,"memory_total":38421312,"rss":-270336},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:55:48.815+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:55:48.815+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 12 reconnect attempt(s)
2023-03-09T23:55:48.815+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:55:48.815+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:56:16.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":246},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":420140}},"memstats":{"gc_next":16826032,"memory_alloc":8535808,"memory_total":38525344,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"retry":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:56:21.616+0800	INFO	log/harvester.go:330	File is inactive: E:\code\云原生\git.imooc.com\dessple\pob\micro.log. Closing because close_inactive of 5m0s reached.
2023-03-09T23:56:26.764+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:56:26.764+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 13 reconnect attempt(s)
2023-03-09T23:56:26.764+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:56:26.764+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:56:46.299+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":253},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":450151}},"memstats":{"gc_next":16826032,"memory_alloc":8627496,"memory_total":38617032,"rss":4096},"runtime":{"goroutines":23}},"filebeat":{"events":{"active":1,"added":1},"harvester":{"closed":1,"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68,"filtered":1,"retry":3,"total":1}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:57:16.288+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125},"total":{"ticks":234,"value":234},"user":{"ticks":109}},"handles":{"open":253},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":480140}},"memstats":{"gc_next":16826032,"memory_alloc":8699120,"memory_total":38688656},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":68}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:57:17.429+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:57:17.429+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 14 reconnect attempt(s)
2023-03-09T23:57:17.429+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:57:17.429+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:57:36.551+0800	INFO	log/harvester.go:299	Harvester started for file: E:\code\云原生\git.imooc.com\dessple\pob\micro.log
2023-03-09T23:57:36.974+0800	INFO	beater/filebeat.go:515	Stopping filebeat
2023-03-09T23:57:36.974+0800	INFO	beater/crawler.go:148	Stopping Crawler
2023-03-09T23:57:36.974+0800	INFO	beater/crawler.go:158	Stopping 1 inputs
2023-03-09T23:57:36.974+0800	INFO	[crawler]	beater/crawler.go:163	Stopping input: 9579789163401830746
2023-03-09T23:57:36.974+0800	INFO	input/input.go:136	input ticker stopped
2023-03-09T23:57:36.974+0800	INFO	log/harvester.go:326	Reader was closed: E:\code\云原生\git.imooc.com\dessple\pob\micro.log. Closing.
2023-03-09T23:57:36.974+0800	INFO	beater/crawler.go:178	Crawler stopped
2023-03-09T23:57:36.974+0800	INFO	[registrar]	registrar/registrar.go:132	Stopping Registrar
2023-03-09T23:57:36.974+0800	INFO	[registrar]	registrar/registrar.go:166	Ending Registrar
2023-03-09T23:57:36.974+0800	INFO	[registrar]	registrar/registrar.go:137	Registrar stopped
2023-03-09T23:57:36.975+0800	INFO	[monitoring]	log/log.go:153	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":125,"time":{"ms":125}},"total":{"ticks":234,"time":{"ms":234},"value":234},"user":{"ticks":109,"time":{"ms":109}}},"handles":{"open":254},"info":{"ephemeral_id":"4705d672-0e83-466e-863a-1ca737276c6d","uptime":{"ms":500827}},"memstats":{"gc_next":16749904,"memory_alloc":8470328,"memory_total":38835304,"rss":43696128},"runtime":{"goroutines":13}},"filebeat":{"events":{"active":70,"added":72,"done":2},"harvester":{"closed":2,"open_files":0,"running":0,"started":2},"input":{"log":{"files":{"truncated":1}}}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":0,"events":{"active":68,"filtered":4,"published":68,"retry":629,"total":72}}},"registrar":{"states":{"current":1,"update":2},"writes":{"success":2,"total":2}},"system":{"cpu":{"cores":12}}}}}
2023-03-09T23:57:36.975+0800	INFO	[monitoring]	log/log.go:154	Uptime: 8m20.8273562s
2023-03-09T23:57:36.975+0800	INFO	[monitoring]	log/log.go:131	Stopping metrics logging.
2023-03-09T23:57:36.975+0800	INFO	instance/beat.go:456	filebeat stopped.
